# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb390567462221c8e9ca433337a8fa3dc67243c42b97d49ba7c66c9902d07aa694d441b1221fda28db0549b7b5fec55647f4cc07bae618b5788f21746dbcba5

test:
  secret_key_base: b49ecde88917467c2bf0624aa5ef6f35b246b63414bef12fff05b1d219698a9de56ef28e3f2b736b51bc46dbfbd7e1d882b8b01a12c7fce9a906394a7c77ad0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
